module Datadog
  class Error < StandardError
  end

  class JSONLogger < Logger
    @default_formatter: untyped

    def initialize: (?untyped output) -> void

    private

    def default_output: () -> untyped
  end
end
