module Datadog
  class Error < StandardError
  end

  class JSONLogger < Logger
    @default_formatter: untyped

    def initialize: (?(_IO | ::StringIO | ::File) output) -> void
    def default_output: () -> _IO
  end
end
