module Datadog
  class Error < StandardError
  end

  class JSONLogger < Logger
    @default_formatter: singleton(Loggers::JSONFormatter)

    def self.configure: () -> yield(JSONLoggerConfiguration) -> void
    def initialize: (?IO | StringIO | File | NilClass output) -> void
    def config: () -> JSONLoggerConfiguration

    private

    def default_output: () -> IO
  end
end
