FROM ruby:3.0.1-alpine

RUN apk add --no-cache build-base git

COPY . /gem
WORKDIR /gem

RUN chmod +x nexus_release.sh

RUN bundle install
RUN gem install nexus
RUN gem build datadog-json_logger.gemspec

CMD ["/bin/sh", "/gem/nexus_release.sh"]
