name: Nexus upload

on:
  push:
    tags:
      - '*'
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build gem

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Build Gem
        run: gem build datadog-json_logger.gemspec

      - name: Set Gem File Output
        id: set_gem_file
        run: echo "::set-output name=gem_file::$(ls -1 | grep '.gem$' | head -n 1)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy with Nexus using Ruby 3.0.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Custom Docker Image
        run: docker build -t nexus-uploader -f Dockerfile.nexus .

      - name: Run Custom Docker Container
        env:
          NEXUS_DEPLOY_URL: ${{ secrets.NEXUS_DEPLOY_URL }}
          NEXUS_CREDENTIALS: ${{ secrets.NEXUS_CREDENTIALS }}
        run: docker run -e NEXUS_DEPLOY_URL -e NEXUS_CREDENTIALS nexus-uploader