name: Nexus upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.2'
    name: Install and build gem

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1

      - name: Build Gem
        run: gem build datadog-json_logger.gemspec

      - name: Build Custom Docker Image
        run: docker build -t nexus-uploader -f Dockerfile.nexus .

      - name: Run Custom Docker Container
        env:
          NEXUS_DEPLOY_URL: ${{ secrets.NEXUS_DEPLOY_URL }}
          NEXUS_CREDENTIALS: ${{ secrets.NEXUS_CREDENTIALS }}
        run: docker run -e NEXUS_DEPLOY_URL -e NEXUS_CREDENTIALS nexus-uploader