name: Nexus upload

on:
  push:
    tags:
      - '*'
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle install

      - name: Build Gem
        run: |
          gem build datadog-json_logger.gemspec
          echo "gem_file=$(ls -1 | grep '.gem$' | head -n 1)" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy with Nexus using Ruby 3.0.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Install Nexus Gem
        run: |
          gem install nexus

      - name: Deploy to Nexus
        run: |
          gem nexus --url ${{ secrets.NEXUS_DEPLOY_URL }} --credential ${{ secrets.NEXUS_CREDENTIALS }} ${{ env.gem_file }}