name: Nexus upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and compile gem
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Gem
        run: |
          gem build datadog-json_logger.gemspec
          echo "gem_file=$(ls -1 | grep '.gem$' | head -n 1)" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy with Nexus using Ruby 3.0.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Install Nexus Gem
        run: |
          gem install nexus

      - name: Deploy to Nexus
        run: |
          gem nexus --url ${{ secrets.NEXUS_DEPLOY_URL }} --credential ${{ secrets.NEXUS_CREDENTIALS }} ${{ env.gem_file }}